title: GitHub Pages with jekyll
author: pilarblancoraynal
email: smartwebmixpro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just proving how to make github pages with jekyll...

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
